### ISSUE TITLE
Otel extensions being improperly shaded

### ISSUE THREAD

**Issue by nikammerlaan** [ryandens/javaagent-gradle-plugin#167]
~~Due to how OpenTelemetry packages their javaagent package, the otel plugin no longer works. The javaagent creates its own classloader in a subdirectory of the jar, `inst`. This means that the extensions get shaded into the bootstrap classloader and not the agent's classloader.~~

I don't think my description of the problem is actually correct, but there is definitely an issue here. I don't have a good understanding how the process is _supposed_ to work, but what I'm finding is that my extension is being shaded into the top level of the jar. The code implies that it's supposed to end up in the `extensions` directory, but it's just empty. I created a repo with a minimal reproducible example [here](https://github.com/nikammerlaan/otel-extension-test).

**Comment by ryandens** [comment]
Thanks for the reproducer, that was going to be my first ask! I don't use the otel plugin frequently anymore, but i have a test project setup. With all the stabilization work/changes that have gone into OTel since I developed the plugin, it doesn't surprise me that this doesn't work anymore - i'll take a look at upgrading the version of OTel used in the test suite, i thought that was happening automatically with renovate but it appears not.

**Comment by ryandens** [comment]
Btw I tested this with your project to verify the fix 

```diff
 plugins {
     id "java"
     id "application"
-    id "com.ryandens.javaagent-application" version "0.6.1"
-    id "com.ryandens.javaagent-otel-modification" version "0.6.1"
+    id "com.ryandens.javaagent-application" version "0.7.0"
+    id "com.ryandens.javaagent-otel-modification" version "0.7.0"
 }

 repositories {
@@ -10,7 +10,7 @@ repositories {
 }

 dependencies {
-    otel group: "io.opentelemetry.javaagent", name: "opentelemetry-javaagent", version: "1.11.1"
+    otel group: "io.opentelemetry.javaagent", name: "opentelemetry-javaagent", version: "2.8.0"
```

**Comment by ryandens** [comment]
>  I don't think I could stomach manually downloading jars.

It really is the worst 😆
